import java.util.Objects;

public class Item {

    private String name;
    private int weight;

    public Item(String name, int weight) {
        this.name = name;
        this.weight = weight;
    }

    public Item(String name) {
        this(name, 0);
    }

    public String getName() {
        return name;
    }

    public int getWeight() {
        return weight;
    }
    /* mine
    public boolean equals(Object anotherItem){
        if(this == anotherItem){
            return true;
        }
        
        if(!(anotherItem instanceof Item)){
            return false;
        }
        Item newItem = (Item) anotherItem;
        if(this.getName().equals(newItem.getName()) && this.getWeight() == newItem.getWeight()){
            return true;
        }
        return false;
        
    }*/

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Item other = (Item) obj;      
        if (!Objects.equals(this.name, other.name)) {
            return false;
        }
        return true;
    }
    
    
    
    //mine
    /*public int hashCode(){
        return Objects.hash(this.name,this.weight);
    }*/

    //generated by Netbeans
    @Override
    public int hashCode() {
        int hash = 7;
        hash = 47 * hash + Objects.hashCode(this.name);
        return hash;
    }
    
    public String toString(){
        return this.getName() + " (" + this.getWeight() + "kg)";
    }
    
}
